# Generated by Django 4.0 on 2023-04-01 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0017_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
