# Generated by Django 4.0 on 2023-04-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0019_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
